apiVersion: v1
kind: Namespace
metadata:
  name: 3tierapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: 3tierapp
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: public.ecr.aws/e0i5p7n6/frontend:latest
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "backend:8080"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: 3tierapp
spec:
  ports:
  - port: 8080
    nodePort: 30001
    name: TCP
  type: NodePort
  selector:
   role: frontend