AWSTemplateFormatVersion: '2010-09-09'
Description: Attach IAM Role to an EC2
Parameters:
  AMI:
    Type: AWS::EC2::Image::Id
    Description: AMI ID is used to create an ec2 instance of corresponding OS.
    Default: "ami-0a1179631ec8933d7"
  InstanceType:
    Type: String
    Default: t2.micro
    Description: Selecting an instance type that meets our computing, memory, networking, or storage needs.
  KeyName:
    Type: String
    Default: test_ec2
    Description: We can use a key pair to securely connect to your instance.
  SecurityGroups:
    Type: String
    Default: sg-096e76d2c6315fbaf
    Description: Security Group to add to EC2 Instance.
  EC2VPC:
    Type: AWS::EC2::VPC::Id
    Default: vpc-05d42dad479891e15
Resources:
  Test:
    Type: AWS::EC2::Instance
    DependsOn:
      - "Lists3bkt"
    Properties:
      ImageId: !Ref AMI
      InstanceType:
        Ref: InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds: 
        - Ref: SecurityGroups
      IamInstanceProfile:
        Ref: ListS3BucketsInstanceProfile
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          #sudo su
          yum install httpd -y 
          aws s3 cp s3://cfttemps3bkt/index.html  /var/www/html/index.html
          systemctl status httpd 
          sudo systemctl start httpd
          systemctl status httpd 
  ListS3BucketsInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - Ref: ListS3BucketsRole
  ListS3BucketsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ListS3BucketsPolicy
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action:
          - s3:List*
          - s3:Get*
          Resource: "arn:aws:s3:::cfttemps3bkt/*"
      Roles:
      - Ref: ListS3BucketsRole
  Lists3bkt:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cfttemps3bkt
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
  ListS3BucketsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"

