AWSTemplateFormatVersion: "2010-09-09"
Description: This template is used to create a ec2 instance.
Parameters:
  AMI:
    Type: AWS::EC2::Image::Id
    Description: AMI ID is used to create an ec2 instance of corresponding OS.
    Default: "ami-0a1179631ec8933d7"
  InstanceType:
    Type: String
    Default: t2.micro
    Description: Selecting an instance type that meets our computing, memory, networking, or storage needs.
  KeyName:
    Type: String
    Default: test_ec2
    Description: We can use a key pair to securely connect to your instance.
  SecurityGroups:
    Type: String
    Default: sg-096e76d2c6315fbaf
    Description: Security Group to add to EC2 Instance.
  EC2VPC:
    Type: AWS::EC2::VPC::Id
    Default: vpc-05d42dad479891e15
Resources:
  Raj:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMI
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds: 
        - Ref: SecurityGroups
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          #sudo su
          yum install httpd -y
          systemctl status httpd
          systemctl start httpd
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: "ipv4"
      Scheme: internet-facing
      SecurityGroups:
        - !Ref SecurityGroups
      Subnets:
        - "subnet-04287cde12f035e08"
        - "subnet-01ed866330e76671e"
      Type: "network"
  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: "true"
      HealthCheckIntervalSeconds: 30
      HealthCheckPort: "80"
      HealthCheckProtocol: "TCP"
      HealthCheckTimeoutSeconds: 30
      HealthyThresholdCount: 3
      IpAddressType: "ipv4"
      Protocol: "TCP"
      Port: 80
      TargetType: "instance"
      UnhealthyThresholdCount: 4
      VpcId: !Ref EC2VPC
      Targets:
        - Id: !Ref Raj
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: "TCP"
      