AWSTemplateFormatVersion: "2010-09-09"
Description: This template is used to create a ec2 instance.
Parameters:
  # AMI:
  #   Type: AWS::EC2::Image::Id
  #   Description: AMI ID is used to create an ec2 instance of corresponding OS.
  #   Default: "ami-0a1179631ec8933d7"
  InstanceType:
    Type: String
    Default: t2.micro
    Description: Selecting an instance type that meets our computing, memory, networking, or storage needs.
  # KeyName:
  #   Type: String
  #   Default: test_ec2
  #   Description: We can use a key pair to securely connect to your instance.
  # SecurityGroups:
  #   Type: String
  #   Default: sg-096e76d2c6315fbaf
  #   Description: Security Group to add to EC2 Instance.
  # EC2VPC:
  #   Type: AWS::EC2::VPC::Id
  #   Default: vpc-05d42dad479891e15
Mappings:
  RegionMap:
    us-east-1:
      VPC: vpc-05d42dad479891e15
      ImageId: ami-0a1179631ec8933d7
      keyname: test_ec2
      Securitygroup: sg-096e76d2c6315fbaf
      subnets1: subnet-01ed866330e76671e
      subnets2: subnet-04287cde12f035e08
      AZ1: us-east-1a
      AZ2: us-east-1b 
    us-west-1:
      VPC: vpc-0ac792ea60bb1d83e
      ImageId: ami-031a87d6fc2457605
      keyname: west_ec2
      Securitygroup: sg-01996fadae5cb69d5
      subnets1: subnet-065e33852b4034156
      subnets2: subnet-098da992d6ea053fb
      AZ1: us-west-1a
      AZ2: us-west-1b
Resources:
  Raj:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region",ImageId]
      InstanceType: !Ref InstanceType
      KeyName: !FindInMap [RegionMap, !Ref "AWS::Region",keyname]
      SecurityGroupIds: 
        - !FindInMap [RegionMap, !Ref "AWS::Region",Securitygroup]
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          #sudo su
          yum install httpd -y
          systemctl status httpd
          systemctl start httpd
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: "ipv4"
      Scheme: internet-facing
      SecurityGroups:
        - !FindInMap [RegionMap, !Ref "AWS::Region",Securitygroup]
      Subnets:
        - !FindInMap [RegionMap, !Ref "AWS::Region",subnets1]
        - !FindInMap [RegionMap, !Ref "AWS::Region",subnets2]
        # - "subnet-04287cde12f035e08"
        # - "subnet-01ed866330e76671e"
      Type: "network"
  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: "true"
      HealthCheckIntervalSeconds: 30
      HealthCheckPort: "80"
      HealthCheckProtocol: "TCP"
      HealthCheckTimeoutSeconds: 30
      HealthyThresholdCount: 3
      IpAddressType: "ipv4"
      Protocol: "TCP"
      Port: 80
      TargetType: "instance"
      UnhealthyThresholdCount: 4
      VpcId: !FindInMap [RegionMap, !Ref "AWS::Region",VPC]
      Targets:
        - Id: !Ref Raj
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: "TCP"
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        - !FindInMap [RegionMap, !Ref "AWS::Region",AZ1]
        - !FindInMap [RegionMap, !Ref "AWS::Region",AZ2]
        # - "us-east-1a"
        # - "us-east-1b"
        # - "us-west-1a"
        # - "us-west-1b"
      CapacityRebalance: true
      DesiredCapacity: "2"
      DesiredCapacityType: "units"
      HealthCheckGracePeriod: 200
      LaunchConfigurationName: !Ref LaunchConfiguration
      MaxInstanceLifetime: 87000
      MaxSize: "6"
      MinSize: "2"
      TargetGroupARNs:
        - !Ref MyTargetGroup
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region",ImageId]
      InstanceType: !Ref InstanceType
      KeyName: !FindInMap [RegionMap, !Ref "AWS::Region",keyname]
      SecurityGroups: 
        - !FindInMap [RegionMap, !Ref "AWS::Region",Securitygroup]
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          #sudo su
          yum install httpd -y
          systemctl status httpd
          systemctl start httpd
          cd /var/www/html
          cat << EOL > /var/www/html/index.html
          <!DOCTYPE html>
            <html>
              <head>
                <title>Apache Web Server</title>
              </head>
              <body>
                <h1>Raj Website 1</h1>
                <p>This is a amazon linux 2 Machine.</p>
              </body>
            </html>
          EOL